default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 50

development:
  <<: *default
  database: rubetek_test_development

test:
  <<: *default
  database: rubetek_test_test

production:
  <<: *default
  database: rubetek_test_production
  username: rubetek_test
  password: <%= ENV['RUBETEK_TEST_DATABASE_PASSWORD'] %>
